# Generated by Django 6.0.7 on 2026-07-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='product_price',
        ),
    ]
